apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: 2.10.2
    valuesFile: values.yaml
    releaseName: grafana-loki
    includeCRDs: true


namespace: sharedtooling