apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.2
    valuesFile: values.yaml
    releaseName: ingress-nginx


namespace: ingress-nginx