apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kong
    repo: https://charts.konghq.com
    version: 2.42.0
    valuesFile: values.yaml
    releaseName: kong
    includeCRDs: true

namespace: kong