apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: infra-dev-letsencrypt
  namespace: cert-manage
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: akinolatolulope24@gmail.com
    privateKeySecretRef:
      name: infra-dev-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx